### PR TITLE
Increase underscore version because of CVE-2021-23358 vulnerability

### PR DESCRIPTION
**Pull request by Warkanlock**
It is a high severity vulnerability within this package. It's extremely necessary to update this package and prevent the usage of underscore at ``~1.7.0``

## Why

**CVE-2021-23358**
Vulnerable versions: >= 1.3.2, < 1.12.1
Patched version: 1.12.1

The package underscore from 1.13.0-0 and before 1.13.0-2, from 1.3.2 and before 1.12.1 are vulnerable to Arbitrary Code Execution via the template function, particularly when a variable property is passed as an argument as it is not sanitized.

## Packages affected

Every package that used @ladjs/i18n it's vulnerable to this attack because it's using country-language package in the background and this package it's the one with the vulnerable package version

---

Best Regards!

Feel free to check it out with cross dependencies between projects but so far, this project works with that package version.

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -5,7 +5,7 @@
   "main": "index.js",
   "types": "index.d.ts",
   "dependencies": {
-    "underscore": "~1.7.0",
+    "underscore": "^1.12.1",
```
Comment (adam2k) [inline package.json:8]: Because you're installing `"underscore": "^1.12.1",` and there isn't a `package-lock.json` or `yarn.lock` you'll actually be installing the latest minor release. 

Check out your `npm` packages locally and you should see `"version": "1.13.1",` located at, `node_modules/underscore/package.json`

Comment (Warkanlock) [reply package.json:8]: Yeah, you are right! We would be using 1.13.1 in this case. Thanks for the clarification!

**Comment by theArina** [comment]
Hello, will you merge this ?

**Comment by Warkanlock** [comment]
> Hello, will you merge this?

I cannot merge since I'm not the author, but we can guarantee that the repo is deprecated by the authors. Maybe we should need to plan a new strategy here @adam2k, What do you think?

**Comment by JimmyRowland** [comment]
Updating underscore to `1.13.1` did not solve my issue.

I am getting this error:

`Error: Cannot find module 'underscore'`

image

**Comment by Warkanlock** [comment]
> Updating underscore to `1.13.1` did not solve my issue.
> 
> I am getting this error:
> 
> `Error: Cannot find module 'underscore'`
> 
> image
> 
> https://github.com/Clever/underscore.deep/blob/master/package.json

This is not a fix for a module that is not found, has to be something else. This PR it's a fix for a vulnerability issue

**Comment by adam2k** [comment]
@Warkanlock I tried to email the company using their webform here: https://global.bdswiss.com/contact/

but I didn't get a response other than an automated message saying that they received my message.  It seems like the owners of this repo are not going to approve or merge this PR.

**Comment by Warkanlock** [comment]
> @Warkanlock I tried to email the company using their webform here: https://global.bdswiss.com/contact/
> 
> but I didn't get a response other than an automated message saying that they received my message. It seems like the owners of this repo are not going to approve or merge this PR.

Maybe it's time to make our own library haha (jk)

**Comment by JimmyRowland** [comment]
underscore.deep does not work with underscore 1.13.1 and country-language depends on both underscore and underscore.deep.
Try force updating underscore
```
  "resolutions": {
    "underscore": "^1.13.1"
  },
```
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by Warkanlock** [comment]
> underscore.deep does not work with underscore 1.13.1 and country-language depends on both underscore and underscore.deep.
> Try force updating underscore
> 
> ```
>   "resolutions": {
>     "underscore": "^1.13.1"
>   },
> ```
> 
> https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

Good catch man, thanks!

**Comment by JimmyRowland** [comment]
Sorry for the confusion.
If you force update underscore to 1.13.1, underscore.deep will return error `Cannot find module 'underscore'`

**Comment by adam2k** [comment]
@Warkanlock it might be best to find a different repo.  The library that I am using that has this library as a dependency is `email-templates`, but they patched the CVE with a different dependency. 

https://github.com/forwardemail/email-templates/commit/6eeb95e0792db26fecb171ab243aa57d0e81195d

**Review by alatzidis — APPROVED** [review]

**Comment by abdulgit2021** [comment]
@alatzidis can you please publish the latest version as you have merged this PR!

**Comment by alatzidis** [comment]
Released

**Comment by abdulgit2021** [comment]
thanks @alatzidis but still I see version 0.1.7 available.

**Comment by abdulgit2021** [comment]
@alatzidis appreciate if you can publish the latest version.. thanks!
